apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/version: 2.15.0
  name: kube-state-metrics
  namespace: kube-system
spec:
  type: NodePort
#  clusterIP: None
  ports:
  - name: http-metrics
    port: 8080
#    targetPort: http-metrics
    targetPort: 8080
    nodePort: 31666
    protocol: TCP
#  - name: telemetry
#    port: 8081
#    targetPort: telemetry
  selector:
    app.kubernetes.io/name: kube-state-metrics
