# 使用官方 OpenJDK 17 基础镜像
FROM eclipse-temurin

# 设置工作目录
WORKDIR /app

# 复制构建的 JAR 文件（确保路径与你的构建输出一致）
COPY ./springboot-helloworld-0.0.1.jar hello.jar 

# 暴露端口（与 application.properties 中的 server.port 一致）
EXPOSE 8090

# 启动命令（添加 JVM 参数优化）
ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=prod", "-Dserver.port=8090", "hello.jar"]
