apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 3
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: my-nginx-1
        imagePullPolicy: IfNotPresent   #如果本地存在镜像，则使用本地镜像；否则从远程仓库拉取
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        ports:
        - containerPort: 80
        volumeMounts:
          - name: timezone
            mountPath: /etc/localtime                           # 挂载到容器的目录
      volumes:
         - name: timezone
           hostPath: 
             path: /usr/share/zoneinfo/Asia/Shanghai
