# service配置文件如下
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx
spec:
  selector:
    app: nginx-deploy
  ports:
  - port: 7878
    targetPort: 80
    name: web
  type: NodePort

